trigger:
  batch: false
  branches:
    include:
      - master
      - ci-*
  tags:
    include:
      - v*-ci

jobs:
- job: build_atf
  pool:
    vmImage: 'ubuntu-18.04'
  container: sigmaris/aarch64-linux-crossbuilder:latest
  steps:
  - checkout: none  #skip checking out the default repository resource
  - script: |
      set -e
      git clone --branch v2.4 https://github.com/ARM-software/arm-trusted-firmware.git
      cd arm-trusted-firmware
      make realclean
      make -j$(getconf _NPROCESSORS_ONLN) CROSS_COMPILE=aarch64-linux-gnu- PLAT=rk3399 bl31
      cp build/rk3399/release/bl31/bl31.elf '$(Build.ArtifactStagingDirectory)'
    displayName: Build arm-trusted-firmware bl31.elf for rk3399
  - task: PublishBuildArtifacts@1
    displayName: 'Publish arm-trusted-firmware bl31.elf'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/bl31.elf'
      artifactName: atf
- job: build_uboot
  dependsOn: build_atf
  condition: succeeded()
  pool:
    vmImage: 'ubuntu-18.04'
  container: sigmaris/aarch64-linux-crossbuilder:latest
  strategy:
    maxParallel: 2
    matrix:
      spi:
        img1type: rkspi
        img1name: spi_idbloader.img
        img2name: spi_u-boot.itb
        envname: spi_default_env.img
        artifact: spi_u-boot
      mmc:
        img1type: rksd
        img1name: mmc_idbloader.img
        img2name: mmc_u-boot.itb
        envname: mmc_default_env.img
        artifact: mmc_u-boot
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      artifactName: atf
      downloadPath: '$(System.DefaultWorkingDirectory)'
  - script: |
      set -e
      export BL31="$(realpath $(System.DefaultWorkingDirectory)/atf/bl31.elf)"

      # Configure U-Boot
      make mrproper
      make rockpro64-rk3399_defconfig

      # Build U-Boot
      make -j$(getconf _NPROCESSORS_ONLN) CROSS_COMPILE=aarch64-linux-gnu-

      # Make idbloader.img
      tools/mkimage -n rk3399 -T $(img1type) -d tpl/u-boot-tpl.bin:spl/u-boot-spl.bin $(img1name)

      # Copy built-in env object and extract env data
      cp env/built-in.o built_in_env.o
      aarch64-linux-gnu-objcopy -O binary -j ".rodata.default_environment" built_in_env.o

      # Replace null terminator in built-in env with newlines
      tr '\0' '\n' < built_in_env.o | sed '/^$/d' > built_in_env.txt

      # Make built-in env image with correct CRC
      tools/mkenvimage -s 0x8000 -o $(envname) built_in_env.txt

      # Copy built artifacts to artifact staging directory
      cp $(img1name) '$(Build.ArtifactStagingDirectory)'
      cp u-boot.itb '$(Build.ArtifactStagingDirectory)/$(img2name)'
      cp $(envname) '$(Build.ArtifactStagingDirectory)'
    displayName: Build u-boot binaries
  - script: |
      set -e
      padsize=$((0x60000 - 1))
      img1size=$(wc -c <"$(img1name)")
      [ $img1size -le $padsize ] || exit 1
      dd if=/dev/zero of=$(img1name) conv=notrunc bs=1 count=1 seek=$padsize
      cat $(img1name) u-boot.itb > '$(Build.ArtifactStagingDirectory)/spi_combined.img'
      tools/mkimage -C none -A arm -T script -d scripts/flash_spi.cmd '$(Build.ArtifactStagingDirectory)/flash_spi.scr'
      tools/mkimage -C none -A arm -T script -d scripts/erase_spi.cmd '$(Build.ArtifactStagingDirectory)/erase_spi.scr'
    displayName: Create single SPI image with u-boot.itb at 0x60000
    condition: eq(variables['img1type'], 'rkspi')
  - task: PublishBuildArtifacts@1
    displayName: 'Publish idbloader.img and u-boot.itb'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: '$(artifact)'
- job: spi_flash_img
  dependsOn:
  - build_uboot
  condition: succeeded()
  pool:
    vmImage: 'ubuntu-18.04'
  container: sigmaris/aarch64-linux-crossbuilder:latest
  strategy:
    maxParallel: 2
    matrix:
      flash:
        script_name: flash_spi
      erase:
        script_name: erase_spi
  steps:
  - checkout: none  #skip checking out the default repository resource
  - task: DownloadBuildArtifacts@0
    displayName: 'Download mmc_u-boot artifacts'
    inputs:
      artifactName: mmc_u-boot
      downloadPath: '$(System.DefaultWorkingDirectory)'
  - task: DownloadBuildArtifacts@0
    displayName: 'Download spi_u-boot artifacts'
    inputs:
      artifactName: spi_u-boot
      downloadPath: '$(System.DefaultWorkingDirectory)'
  - script: |
        set -e
        cp '$(System.DefaultWorkingDirectory)/spi_u-boot/$(script_name).scr' boot.scr
        cp '$(System.DefaultWorkingDirectory)/spi_u-boot/spi_combined.img' spi_combined.img
        dd if=/dev/zero of=boot.tmp bs=1M count=16
        mkfs.vfat -n u-boot-script boot.tmp
        mcopy -sm -i boot.tmp boot.scr ::
        mcopy -sm -i boot.tmp spi_combined.img ::
        dd if=/dev/zero of=$(script_name).img bs=1M count=32
        parted -s $(script_name).img mklabel gpt
        parted -s $(script_name).img unit s mkpart loader1 64 8063
        parted -s $(script_name).img unit s mkpart loader2 16384 24575
        parted -s $(script_name).img unit s mkpart boot fat16 24576 100%
        parted -s $(script_name).img set 3 legacy_boot on
        dd if='$(System.DefaultWorkingDirectory)/mmc_u-boot/mmc_idbloader.img' of=$(script_name).img conv=notrunc seek=64
        dd if='$(System.DefaultWorkingDirectory)/mmc_u-boot/mmc_u-boot.itb' of=$(script_name).img conv=notrunc seek=16384
        dd if=boot.tmp of=$(script_name).img conv=notrunc seek=24576
        gzip $(script_name).img
    displayName: Create SD card images to flash u-boot to SPI or erase SPI flash
  - task: PublishBuildArtifacts@1
    displayName: Publish SD card image to flash u-boot to SPI or erase SPI flash
    inputs:
      pathToPublish: '$(script_name).img.gz'
      artifactName: spi_u-boot
- job: github_release
  dependsOn:
  - spi_flash_img
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'), endsWith(variables['Build.SourceBranch'], '-ci'))
  pool:
    vmImage: 'ubuntu-18.04'
  container: sigmaris/aarch64-linux-crossbuilder:latest
  steps:
  - checkout: none  #skip checking out the default repository resource
  - task: DownloadBuildArtifacts@0
    displayName: 'Download mmc_u-boot artifacts'
    inputs:
      artifactName: mmc_u-boot
      downloadPath: '$(System.DefaultWorkingDirectory)'
  - task: DownloadBuildArtifacts@0
    displayName: 'Download spi_u-boot artifacts'
    inputs:
      artifactName: spi_u-boot
      downloadPath: '$(System.DefaultWorkingDirectory)'
  - script: |
      cp $(System.DefaultWorkingDirectory)/mmc_u-boot/* $(System.DefaultWorkingDirectory)/spi_u-boot/* '$(Build.ArtifactStagingDirectory)'
    displayName: Copy build artifacts to staging directory
  - task: GithubRelease@0
    displayName: 'Create Github release with assets'
    inputs:
      gitHubConnection: sigmaris_token
      repositoryName: sigmaris/u-boot
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'auto'
      title: 'rockpro64 u-boot $(Build.SourceBranchName)'
      assets: '$(Build.ArtifactStagingDirectory)/*'
